"""
Django settings for abac_poc project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-q%pe79eetrlr1vibse4--02*c7%jo5@v9eka5c4r64+7bu3qq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_mongoengine',
    'user',
    'company',
    'opportunity'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'opportunity.middleware.KeycloakMiddleware',
]


ROOT_URLCONF = 'abac_poc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'abac_poc.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
       'default': {
           'ENGINE': 'django.db.backends.sqlite3',
           'NAME': 'abac-poc',
       }
   }


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

DB_CONNECTION_STRING = 'mongodb://localhost:27017/abac_poc'
DB_REPLICA_SET = {}
from mongoengine import connect
from mongoengine.connection import disconnect

def setup_connection():
    from django.conf import settings

    # Disconnect any previous session if any
    disconnect(alias=settings.DB_CONNECTION_STRING)

    try:
        connect(host=settings.DB_CONNECTION_STRING, **settings.DB_REPLICA_SET)
    except ConnectionError as conn_exc:
        print('DB Error: {}'.format(str(conn_exc)))
        exit(1)

setup_connection()


# Excempt list - URL paths that doesn't need Keycloak Authorization
KEYCLOAK_BEARER_AUTHENTICATION_EXEMPT_PATHS = [
    'admin', 'accounts',
    ]
CONFIG_DIR = os.path.join(os.path.dirname(__file__),os.pardir)
KEYCLOAK_CLIENT_PUBLIC_KEY = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkols8lyzvWprOuu5F18kf3bmuFuyaprio23clDQFPtpDoNLXmrA24DxkEm8B0UI8UZW44BJf8Xzdaahlpz62nYuDnB8Pf5s2fkYJ2btSUob7fn1qJRUyVUZy0DFuHTAJP7asc91+pM7VHkc9Z7haWYovO9EP7+3N+qTHB5FORMVevDQojHYryi2Z26j94wAhASH2x+fvnwM06lL5/n0kqIJAgUpSlNliEo25xo3WUGci/wVuVYnnUqLthD6QbZt0Y1XyJXbfTsi7ny/n7peZp6lQiG3A6AZr+byucYxtGNnOBVsWN4HfRwd4OfrBjNgKuwXjxKxKXetPY/QuVu6fvwIDAQAB
-----END PUBLIC KEY-----"""
KEYCLOAK_CONFIG = {
    'KEYCLOAK_REALM': 'Demo',
    'KEYCLOAK_CLIENT_ID': 'demo-client',
    'KEYCLOAK_DEFAULT_ACCESS': 'ALLOW', # DENY or ALLOW
    'KEYCLOAK_AUTHORIZATION_CONFIG': os.path.join(CONFIG_DIR, 'authorization-config.json'),
    'KEYCLOAK_METHOD_VALIDATE_TOKEN': 'DECODE',
    'KEYCLOAK_SERVER_URL': 'http://localhost:8088/auth/',
    'KEYCLOAK_CLIENT_SECRET_KEY': '6cfd707a-ad3e-49a9-8442-f9536550bdf2',
    'KEYCLOAK_CLIENT_PUBLIC_KEY': KEYCLOAK_CLIENT_PUBLIC_KEY,
}